sudo: false
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
deploy:
  provider: rubygems
  api_key:
    secure: ie2bRSmqDnlyxSMsf0w8CrwpFmnonEdi3koNq1YS5/CRC2lilfVbLnDaQ0RxXCa9XogjDBtrOpFHdfopgdc+YrLTaYgBKHHfCrbKmOjprF7pjyO8LK936/Bz57eK7/JQR/ycIrpqJ8NNvHhLp/BlFE3Mdy5Dax9GXCfsisHMIrJEWMLvedtw9lSc1Vub0z23BeELP6XHebcsAESsz8I5xQVGtPA5IRAL3f66YWw7acD37M1kbuq34ddIL/bDxMYqRJlAcqUr1Xp/gmhvIqQscvpv3TB7Sr/zUTeo5gV7W2IIsCzUZ2i+bCb9mhtGGSXIrS6aTPA69JYyDm/yda6FZ1h/DQKPzJT2P4Atm+30v/xojk4mL3e/sUGft+53+e0naluI/z5CR2YYNGxb3fF9oyMpAmXsMhPm4fmJkROrN7B2Do1mt6UINetnGY+BuAsdt8eACO+ZBH9lOnwdmF9V6Lanrm3Aup9fJXBQwbzv0PhuNUEQheGiHE/jKFVLvr5C6gjbFEVsxvicycKsMYsEhgVwuy/yGhjOpd6nXPtO0PfK9VZV11IWS/OD26eCKTJrrBjUY25DdaODdjnWintXSqqKQTNSeRzo3QJRUgxBz2S9c1D47rnHgWbGGjxfOsjrV/eXEtYIxnptUbOT0ijLb3tBsS2MCt/5WhceKNaBxLQ=
  gem: klaviyo_api
  on:
    tags: true
