sudo: false
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
deploy:
  provider: rubygems
  api_key:
    secure: e4ekipnm1Yak5nFbhdUY+EcvH0epCBlPfuNahlrmXeaDP4moEMZZFwaNq2IIaeiqg+Is2ngpRdisMXUbeP+2uFMbZBCVLBRK8VXRR2EDd6kN9vCTlo5kZPFN4TjODvH/byMsNzt5aoIEQmT6s1J5n8KxGzjClDHqtDTi9S8KaDOugLZGVQfsjGny2VEISOdCmMoWydAG1UcLaKZvxNBKbhc74ojzA5c50i216UJ/towHnKxNb3nPnVSoHXQjsjXbX0M2QDE/mQoZm7uj5e5BttVKWFnV/KzPv5tbUmlwv0ycW64B+Nqx1VyezgtsbtxzNK7FavYW0JkRmSmXuUeu3G+vV6tW1y0iQakvaeXw4+d8AX6T5nra+dYmcsSYi+uq8toAGnTIznVrf9prI/IgBO8c6J5txN9CLUwvBFj5dyDZ9Lct5p0ZexCImLsvZT3hfFRczh16AIJmcrjSiTGtXzK9zE6RrpQiFTRySmM8xu6pDeYjGYfrO5eFFcf3Dsjb1PMh1+FjOwXANDFLFgc6RxSm98WACi9vdw6A009q2GtvTzcvlzEsNYSeSja46jVQ6Gttg5qivt8Y8yK524yB+w302j8vDl5UYD0jehNm6py5jtwa0O+LsrOBrYZcjH9SEC5QijA0hQjK1hUPWCSia13xgA6oQp3DAeVHs3VkSek=
  gem: klaviyo_api
  on:
    tags: true
    repo: rewindio/klaviyo_api
