sudo: false
language: ruby
cache: bundler
before_install:
- gem update --system
- gem install bundler
deploy:
  provider: rubygems
  api_key:
    secure: XKZrn5ChvG8+M4rHtP81nmxmEkhQJe5Nn/U3eG+qzKszOumuSljHBVLB+A/pjGFESL9CWe1/MIh4KN3RMaUWE0vMTFKsOKNrXID7M2dvAx5JzEKly1ByHKkeh0YOWdSQfLrbNu2TO7XWX/DrUMwBezTlMBnt9St5eglQrwigLZle81rJw/5RJHCUstRNFJ03e4Afh9HaMD3kSg0JoX2xAPyfxMVV6sxj4jEmVsDBPuB2jcRZpLdBrQ1tPx03RxhyJd6GoIalbukAX+RhTGg/SNLmJAyzVnf9qgNKvrDRvf66UJoY0j9ft+BfVFIdG4eiMKfWG4gCIC00v7pMd/zzdwlOI9gxvQoZ+incfVgX8EoIuarV7NZcrKhglzMhPCH89quohyRibTl5cXJ7o9kSGYh9/T0oSLcP3aZ7zTEGej0VTuMs7Z5M7CeHKOB16Jmw2/e8v8ivoJHXks3YF45SWrkel056fU2QlKzWrenNRV3v+uAaUf8pK2x2WhgjOwLAfr0ZPXXl+dDaNWjYSsUy55XRng5GDXbAIMTlYVleFKBQvondEjYNCSF0APsDh9TR33x1OQnVM/sPLFRcK1YA4x8K4AOlix+GxM02o1z2o6DQNhhdzp8Iy+Vy7xpkVAe82HkJKvjdUnqUkeF6CVt9It7S9QbmU6rmpqPoun5LZgg=
  gem: klaviyo_api
  on:
    tags: true
