sudo: false
language: ruby
cache: bundler
before_install:
- gem update --system
- gem install bundler
deploy:
  provider: rubygems
  api_key:
    secure: Lv4pFz0E1SEM4yQApgplVZ33CG/cXAYgQJynu5jtkkwvqaLz1hG4gsk+KVcUBZy6SyovXrRBF6Z9GErmWN6NoPjQKMQ+jqJTwzvy04DNU4NVCXUcLxpE6vKOxeybor3EzI9NtvqrOXnYcmS4F8QeKaxwaZTB4UZEs2bCtQaZiapWFT5lucyc4KUevp3N9K2fO0xvubpVyhfjKIyn6yNElF5civYCaIFbCQbDazemUGBTZe2EYAQMyJVp4kdIHAP8iJdhj7znTzLNPRq10dzmKI0N/kETTylp662NjBpei2Smg7yW11u0Zu9AaDedAH19qJJpN52pNAgCL3zED1GGowOzLzsFgP4ndX23yug10e0CaimU3a7du3r1u5I9AA+IyN9ucU1kSREo/TSrkB1pbXRFomL70WFGiMb1mfZ5ui33FDRUW8+Jo/8kZ+Hm8JK+7xN4BZUFSFWMixuUF9TWjBWd9hpidg3UqIH4tRjYiT+Qp/84d7RvttAcw7CvNss8C+oose3luQeA6lsN+o81ldEcRYIi6lB3YGVqnr8l2PWQd8lp5lkd0m4pi1O5EEJLiZ4nrSn1s170DdbF2prA3OOeQJaQaPPUOXVR6mxvBC1CbFna93kAri6I1DFvTh7RKgxehf+/hsaMVyJAXyXajvI/tt4q67TcpYPiJ3NznmE=
  gem: klaviyo_api
  on:
    tags: true
    repo: rewindio/klaviyo_api
