sudo: false
language: ruby
cache: bundler
before_install:
- gem update --system
- gem install bundler
deploy:
  provider: rubygems
  api_key:
    secure: ldyCijuxiDnFxIKEc9s7Ry3jHafX5RWJ76vYzB0vqGbkiHRkfizDCPD7ueV3LJUSiW6cDirxkF3hyaF3I17vAPKtoXnUZPMADIlI4HCQc6ZwGZ2iyu3QPhEreojpzGQDzpNJ3Kb72hkkbsnTkLL0JItjDQCvpVbxEjjSj14mR2/QEeGf6cv+zEZ6UAa+awzaDwAERbIf8SnPEvNjtYWjwckmR4USk+iX4P4a0nnFBwrw2eLiqCrbx1g/sSlTE7FSyQJ3UkOfBUcQ8iVSUlT82U7I9OcutG6UnPKO3VXrWGu/ZEpOZ3XHHVyvimX9ynLCTTBm1H1VnPZKjd6TTU4Yxw9TWnIFYTUAIMOquGRgZ1P8MCCRuWHrQ1lidbTzgZN9gT6+5XgqFB1ms8XLh6HIGFnwjzD/+Dy/dWS2ZAYlocDFyhPx3AFKg9iEC5SGPszFHrRJffJqtGH926NoqARgUKHDTScYZxdglA63MD/9hd9d5iwjrg5GnSHTHHFyFH8dv8+eH82Q8ThligVkbYuCsD1TC3KAMIJdp8MRLVjXH9wWwJuUnJircUBRuiLEfiCAUBvZqor0xih4RaxaFnxt5QSMcbIMGeOkrh7hm0o2bObF8Rrlsfxl3tud6oe2/s8pU2pyuQ+cqOYwntoDRVtw+F8ANqvJfVsL0n6V+1+rWtI=
  gem: klaviyo_api
  on:
    tags: true
    repo: rewindio/klaviyo_api
