sudo: false
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
deploy:
  provider: rubygems
  api_key:
    secure: WHov3NjMZyo/t07jNmDn3CB0VDthACJVF9UJ3bVhtIBRsBRXN2pYdj9vdGUEJ/aK4YucAZodR8YdPtNkyqCA7qVKb/mfFInDOGr9cF8KMiqXhbCdPpaEcfFbzAWE1loL1gRXa0dHWGmCGYg1DQM6F1eZlkBswjcRFpJQAmE/ho1kexA0zIOz+GvOeL6f57CxETwu0LccrQvKdczqTktwMJ4S3PggaEWvKpEYkEADjxfK/fJcUdRirPLxXaVYOPWSa91CJqQpbPqgCw1IqfNeC134UxRzIxtawI83bvykIuM3yNU8Al/enGNtQDbmQETYSy8ue7+r+av43/ETpeIDZMv1CrsGLIBue49JcA/Ac4IusG/whuWhwwFc5wSGrV4Ns+C+tj+vSziY8Zuf5+0cojlzQtyQBBqaJXHXN77YInOkL0XxugLW/f7UNsLW2kaCuqxYHU70gT6K/6C4sTAXKWRUZSHUfYS2hFLPBGLLrOFXWP7POD7xx1vPtaN6Xq09VihNSdjTfYC1IoUe91HpOfgsql8zr98wRs+Nnw2BlwLqFP8eyR8jSCV3VvjR5ci+HBez9xeb6xBKtqM1Axol7zR/SeLAaE3oXw3TEfJRO1PxQVNGBRiGig+KyioW0L9PfYINql0XXsm4tBICMljy6095tQjfEuVrMue0ZO/vB4c=
  gem: klaviyo_api
  on:
    tags: true

