sudo: false
language: ruby
cache: bundler
before_install:
- gem update --system
- gem install bundler
deploy:
  provider: rubygems
  api_key:
    secure: cvHoEd4PVqONWVxTOn5H1YAGDlXIqTs4u7xaQ8rHKVA0Ao9+CTXexgDLvXeSxI44bDdj4qLTuMj2OTIFGz5XJ3eOAeMgVi9LJ8GWTWtH+2hLQUmrxzEujEPmR4tCffGAEAJVO/s3O/yAX5myor71rNx3q+z7/hRkZ4D49A+3kBIV6IMduv23pf4TSrB+pGE8eTJgVrvCUp66x69fxM98Vwk9+gCEk/iwDMC5ysY8SxY2EJN9nERbCGZoTVg9YSYdpaYKA7OCszK7rkpN8VUC7WTk9/f4f4VcVXq24SZGEI4AeMyQwmNmvF72azXfyReBQtjQ2lFXZJ6OUNPNnx+eidWfzDV7e5lm2LkYt64lIp2tqa2OJ0ZAFlPx9pwJ+0j+71BisDAfxl9bIKp2s6z+LE7anwLLSfeVqrLxcqx+4TLj/vWfPwQQT/pLp6DCED4NpWNUXbRkagGo6h+J30R+FdHwHEjpGgC4aU21gYY0+vO8dqsSyqVNsMlJkzGUOcLRs2Pb5ZLmlByyqhMnwpDl1DjUgK14YGcWJGjVCh7qqfNQsd+XDv7+9l1xArZFFrmMTaDotINUJ7F0+QfDn3JTK426Y/hl/6WemX7X7db/cilRzB9DDgmtxMWZdWLbwP6IUrOUP1sd56I36YDFUOvrnKPIX+oz3V22EasHh0xkGAc=
  gem: klaviyo_api
  on:
    tags: true
    repo: rewindio/klaviyo_api
