sudo: false
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
deploy:
  provider: rubygems
  api_key:
    secure: N61kyJSAl23NiDRnX8wuFXMwSmhJt8QDJboeotiCZvrlwvVbEHLxTOWJiYXe3AT7jBSxZawdPGy1LXW9EOf5aWp/P0k6pDTweDBi4hTXS+a38cxhypOcnHaxgmTMpCX8YlaXu/vyOqBvd/k0KKOzqRW/NFolyghmDvNQZ9icNxEfXw16pJqfUahY8/rSmXOKN6OMVHdccaCB+ZHCYxDJ9A9kdUhqDPlEjXQigEY46ztbjqNSyV2JLsDVbwh72c2ut4a0HRefL5MMtAXyvyvB0NkHjLbg+E+vB9yZtdhOTkcZsMMrSfahcRANJePch7UVhS8ccFDZA4VJrQFQqHFDiJ6YjQZB1hiIco/OFuNFyUjfmWDfn8ljNANlG01gXKj73I9Cu2kkDvSs0ndDArCxAEBGZNvQxkVQPbI639zDBKBHmoQudjuYM/6lwOC5CM9Fm4II18qq5n3z+p2MO8C4goedYWrLHGLTtiAPcCZj72FNt4tPsjy/DHwI+KQivXvlcoMYCslbgItMH7y8qYLJ8x4xwllBelI9cB1vhQUC989riEAMfop1Y34N+jXltG/k+zUbN+ir392RWFSjdp1lU22wsflOhBFnPl4/QOOMICnaaFgGRYGeY51MRvJr2ruvGLgUAlBamr58tJ0jU9gb7GigCvcvKQgz9FATGVRKvn8=
  gem: klaviyo_api
  on:
    tags: true
    repo: rewindio/klaviyo_api
